Compatibility issue with Python 3.5
